### ISSUE TITLE
Forum fails to import camper photos from GitHub

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/discourse-meta#10]
When a camper signs in with GitHub, Discourse seems to often fail to import the photo correctly, even though there is a photo on that camper's GitHub account.

I just added S3 keys, which may fix the problem, but I doubt it. I think something is misconfigured within Discourse. Does anyone want to look around and see whether there's an option we need to toggle somewhere?

**Comment by QuincyLarson** [comment]
I've added the ability to upload a custom photo for the time being until we fix this.

**Comment by erlend-sh** [comment]
We only support Gravatars for automatic avatar retrieval at this time:

https://meta.discourse.org/t/google-avatar-not-associating/11879/2?u=erlend_sh

We would however accept PRs for such a feature.

**Comment by m-henderson** [comment]
discourse does not support this feature currently.
