### ISSUE TITLE
Youtube Embed Code not working in new post.

### ISSUE THREAD

**Issue by akshaynaik404** [freeCodeCamp/discourse-meta#11]
Here is link to my post [Forum Post](http://forum.freecodecamp.com/t/what-is-this-devtips-community-everbodys-been-talkin-about/456) .
youtube embed code :
`<p><iframe width="683" height="384" 
src="https://www.youtube.com/embed/-dKh_5vEXRU" frameborder="0" 
allowfullscreen></iframe></p>`

**Comment by raisedadead** [comment]
I think we have to enable this:
https://meta.discourse.org/t/how-to-embed-youtube-and-other-videos/5623

P.S : My account got blocked while trying to test this, I did a huge _**facepalm**_ and now waiting to be unblocked.

**Comment by raisedadead** [comment]
@akshaynaik404 So this has been resolved.

To embed you just need to put the URL of the video in its own line.

Like this:
https://www.youtube.com/embed/-dKh_5vEXRU

**Comment by akshaynaik404** [comment]
Thanks @raisedadead. It works.
