### ISSUE TITLE
Purple links difficult to distinguish

### ISSUE THREAD

**Issue by batjko** [freeCodeCamp/discourse-meta#12]
Hi guys,

I'm not a fan of the purple as it bites the green header very badly.
But specifically, I find any text links which are currently using the purple text color, are almost indistinguishable from normal black text on first sight, if you don't know it is a link. 
I have to squint every time.

Any chance we can use a blue link (and ideally replace the purple in the whole color scheme)?

Cheers

**Comment by QuincyLarson** [comment]
Thanks for the feedback. I've fixed this by reverting to default. @hallaathrad is working on a properly complimentary color scheme that looks good and has sufficient contrast.
