### ISSUE TITLE
Unable to scroll up while new posts are being loading on mobile.

### ISSUE THREAD

**Issue by akshaynaik404** [freeCodeCamp/discourse-meta#14]
When I scroll down on mobile device for more posts. I am unable to scroll up till all the next posts are loaded. Usual experience is that whenever I scroll up the fetching of new posts stops.

I have attached a screenshot when the website freezes till new posts.
![screenshot_2016-05-15-15-13-15](https://cloud.githubusercontent.com/assets/8489816/15273315/3b8f1e58-1ab2-11e6-91a9-0d116fcfa063.png)

**Comment by QuincyLarson** [comment]
This is an issue with Discourse itself. Discourse itself is under heavy development, and this may very well already be fixed in the latest version, which we hope to install soon https://github.com/FreeCodeCamp/discourse/issues/6
