### ISSUE TITLE
forums.freecodecamp.com should redirect to forum.freecodecamp.com

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/discourse-meta#15]
I think we'll need to do this within the Digital Ocean server itself.

**Comment by ghost** [comment]
@QuincyLarson Would you want freecodecamp.com/forum to redirect also?

**Comment by bishisht** [comment]
@atjonathan I think this will be good too :) What do you think @QuincyLarson

**Comment by QuincyLarson** [comment]
I am not sure where this redirect is happening, but it doesn't seem to be happening in nginx or on digital ocean. @BerkeleyTrue do you know where we've configured forum to redirect to our discourse instance?

**Comment by BerkeleyTrue** [comment]
@QuincyLarson  That's happening on Cloudflare

**Comment by BerkeleyTrue** [comment]
We've decided to kill the forums url for now. We'll revisit when I've clear up my list of things to work on and have time to dive into discourse.

Happy Coding

**Comment by m-henderson** [comment]
@BerkeleyTrue  thanks 👍
