### ISSUE TITLE
Error 521

### ISSUE THREAD

**Issue by m-henderson** [freeCodeCamp/discourse-meta#16]
When accessing the forum through [https://forum.freecodecamp.com/](url) I get an error 521. I am guessing that the website is not supposed to be accessed through https but somehow yesterday I was directed to it. 

Maybe we can redirect all https request to keep this issue from arising. 
![git](https://cloud.githubusercontent.com/assets/16070192/15401053/75e7e806-1db3-11e6-9802-f295818eff79.png)

your thoughts?

**Comment by ghost** [comment]
@m-henderson This was addressed in freecodecamp/FreeCodeCamp#8706 and freecodecamp/FreeCodeCamp#8708. The forum is not yet setup with `https`.

**Comment by m-henderson** [comment]
Okay, sorry about that!

**Comment by ghost** [comment]
@m-henderson No problem! Happy Coding :coffee: :computer: :+1:
