### ISSUE TITLE
Could the links be more obviously link-y?

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/discourse-meta#17]
I noticed today that it's really quite hard to tell when text is a link.  I had to look at my monitor from a different angle to even notice that it was a slightly different color.  Could we pretty-please make it a brighter green?

**Comment by GreatDanton** [comment]
or make them underlined

**Comment by justincorrigible** [comment]
done and done :) Thank you both! please check it out and let me know if it's sufficient. Closing unless otherwise requested  :+1:
