### ISSUE TITLE
Request: PHP Category

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/discourse-meta#18]
Copy of message:

> Had a user ask a question about PHP in the forum. The question was asked in the camper lounge, I was going to refer him to a part of the forum where he could get PHP specific help and noticed that there was not a PHP Help subforum under the Free Code Camp category.
> What are your thoughts on adding this to the forum ? Free Code Camp > PHP Help

Requested by @m-henderson

**Comment by zainabr1** [comment]
@atjonathan Hey, My guess is that there isn't a _Free Code Camp > PHP Help_ is because Free Code Camp doesn't teach PHP..

A help category for PHP will be useful.

**Comment by bishisht** [comment]
@QuincyLarson What do you think for fixing above?

**Comment by m-henderson** [comment]
All, thank you for your input! We are going to look into this and make a decision accordingly. Thanks again for the input :smile:
