### ISSUE TITLE
Incorrect Icon

### ISSUE THREAD

**Issue by m-henderson** [freeCodeCamp/discourse-meta#19]
When bookmarking forum.freecodecamp.com to my home screen it shows what  I believe to be a discourse icon. Look at the very top row in the picture third icon from left.  I am using a chrome browser on droid turbo 2.
![screenshot_20160528-233605](https://cloud.githubusercontent.com/assets/16070192/15631566/032e573e-2536-11e6-8524-1d178f2f83c6.png)

**Comment by QuincyLarson** [comment]
Yes - I believe this can be configured in the meta data section of the forum.

**Comment by m-henderson** [comment]
Looking into this.

**Comment by m-henderson** [comment]
@QuincyLarson hey, I know how to change this, I just need an image that is 144 x 144 and a link to the image and we will be good to go.

**Comment by m-henderson** [comment]
I have fixed this issue.... my own issue lol. I guess it's true, you never know where life will take you! :smile: 
![screenshot_20160622-124618](https://cloud.githubusercontent.com/assets/16070192/16289243/fc7e868e-38b8-11e6-9d9f-5f9972e45b5e.png)
