### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/discourse-meta#21]
I am using Chrome version 51.0.2704.63

When trying to reply to `Lets Discuss your "Twitch.tv App"` I get:

`500 Internal Server Error`

When clicking on a link that isn't in my own post I get:

`The forum.freecodecamp.com page isn’t working`
`forum.freecodecamp.com is currently unable to handle this request.`
`HTTP ERROR 500`

This happens when I click any link not posted by myself. Even @QuincyLarson 's link to this repo.

**Comment by Bouncey** [comment]
Hmm... now it seems to have resolved itself...?

**Comment by Bouncey** [comment]
I have another 500 error. This time just navigating to `forum.freecodecamp.com` I am presented with a blank page. 

console shows only `GET http://forum.freecodecamp.com/ 500 (Internal Server Error)`

**Comment by m-henderson** [comment]
its happening again. I am getting the 500 internal error on two different browsers.

**Comment by sludge256** [comment]
Just relaying a related message:

> considering that hammering the request repeatedly makes it go through, my money is on overloaded server

https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=5751daca434455107d4c6a42

**Comment by BerkeleyTrue** [comment]
![digitalocean_-_droplet](https://cloud.githubusercontent.com/assets/6775919/15794822/b06325ea-29a2-11e6-8ad4-ad112f480dff.png)

This is over a 24 hour period. Doesn't seem like the server is breaking a sweat. Looking at top, it seems like the memory usage is also low.

**Comment by m-henderson** [comment]
I am going to go ahead and close this issue. We have been monitoring it for 24 hours and everything appears to be functioning normally.
