### ISSUE TITLE
Authorization error on forums.freecodecamp.com

### ISSUE THREAD

**Issue by sludge256** [freeCodeCamp/discourse-meta#24]
You can access the forum via forums.freecodecamp.com (as opposed to forum) but you can't sign up or log in.

Error message:

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by 727NatureMan** [comment]
Having the same issue here, are you using a mobile device? Also when I log in it says "Authentication is complete. Close this window to continue." But it never actually logs me in.

**Comment by m-henderson** [comment]
please use the default forum.freecodecamp.com to access the forum while i check this out.

**Comment by m-henderson** [comment]
resolved. entering the correct url to the forum navigates you to the forum.

**Comment by Don-E-S** [comment]
How do I join the FCC forum?
The video goes so fast I cannot follow or even begin. Where do I start?

**Comment by m-henderson** [comment]
@Don-E-S this repo is for issue recording that corresponds to the discourse instance. If you need assistance please request it in the chat room ( https://gitter.im/FreeCodeCamp/FreeCodeCamp?source=all-rooms-list )
go to https://forum.freecodecamp.com and Click sign in to login to the forum with your github account.
