### ISSUE TITLE
Text only partially visible on reply box

### ISSUE THREAD

**Issue by itsdeadguy** [freeCodeCamp/discourse-meta#25]
This is happening to me on firefox 47, mint 17.3
As you can see in the screenshot, half of my post gets "eaten" by some sort of negative margin. I have to rely on the preview box to ensure my post is all there.
[Screenshot](http://i.imgur.com/p9K82qX.png).

Once i click the post button, my post shows up fine.

**Comment by m-henderson** [comment]
what operating system are you using ? Also, have you tried clearing your cash? Have you tried on other browsers?

**Comment by itsdeadguy** [comment]
Like i said, this is Mint 17.3. Cache is cleaned on exit every time. Will get back to you re: other browsers.

**Comment by itsdeadguy** [comment]
Just dropped by to say the reply box is now working as expected on my end

**Comment by m-henderson** [comment]
@CadaverLab ok, great! :+1: thanks for bringing attention to this!
