### ISSUE TITLE
Finalize color scheme

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/discourse-meta#3]

**Comment by justincorrigible** [comment]
How do I gain access to start working on this?

**Comment by QuincyLarson** [comment]
@hallaathrad I've given you admin access. Please let me know if I can help you find anything.

**Comment by justincorrigible** [comment]
Yep. Noticed... just been super busy at work. Will probably be able to clear this one tonight.

**Comment by QuincyLarson** [comment]
I normalized the colors of the topics so at least they all look distinct, and all subcategories are the same uniform bronze color. Once we figure out a color scheme we can hopefully bulk-update these subcategories.

**Comment by justincorrigible** [comment]
Seems like we've reached a good point, considering nobody has complained about it 💃
Went a bit over colours and into CSS itself. A lot of the spacing and detailing of the platform itself felt a bit... unfinished. I'll keep an eye out for little adjustments that may be required.

Closing this issue for the time being :)
