### ISSUE TITLE
Admin Account is unable to change ownership of topic

### ISSUE THREAD

**Issue by Rafase282** [freeCodeCamp/discourse-meta#34]
I was able to change ownership of topics before as an admin, yet that is no longer the case even for topics that I actually own.

![Imgur](http://i.imgur.com/cHIftzQ.png)

I get that message every time I try that, even after login off and back on.

**Comment by ghost** [comment]
I am unable to even see the changing ownership button.

**Comment by m-henderson** [comment]
looking into this now.

**Comment by m-henderson** [comment]
I am waiting for feed back now

**Comment by m-henderson** [comment]
Have not received any feedback yet, will contact them again.

**Comment by SidVal** [comment]
You are using an outdated version of discourse.
You must upgrade to the latest version, and try again.
It is also important to mention what plugins used in discourse.

Regards
