### ISSUE TITLE
Forums unstable

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/discourse-meta#35]
ref https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9765

**Comment by BerkeleyTrue** [comment]
Possible running into hardware limits. I don't have enough rails experience to know how much traffic it should handle reliably.

**Comment by m-henderson** [comment]
do you know how many unicorn workers we have set for the instance  ? viewing the unicorn.conf.rb file will show you how many, i am trying to narrow down our options.

**Comment by QuincyLarson** [comment]
@m-henderson As I said on the phone earlier, I think we should leave Discourse's code alone. So far we've done no custom configuration outside of the admin panel. This is an issue with Discourse itself. Thanks for reaching out to their support and sharing those error messages with them.

These are the same symptoms we had about a month ago. These symptoms went away when we doubled the size of the instance. It sounds like the underlying issue persists, and increasing the size of the instance only delayed this issue cropping back up.

**Comment by m-henderson** [comment]
@QuincyLarson I agree, just wanted to take in all possibilities here. :smile:

**Comment by m-henderson** [comment]
@QuincyLarson @BerkeleyTrue  we are getting good response from the discourse team about the issue, as always, so we should figure out what the problem is soon.

**Comment by P1xt** [comment]
Most of the issues I observed last week were explicitly "500" errors. What I'm seeing this morning is a new facet of probably this same issue. Screenshot below:

![seek and destroy basic alogorithm scripting help free code camp javascript help free code camp forum](https://cloud.githubusercontent.com/assets/322175/16987594/b2a04dae-4e52-11e6-92f9-862047ef6f19.png)

**Comment by P1xt** [comment]
Nevermind, it's just another "look" for the same error. Dev console shows

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://forum.freecodecamp.com/t/4477/19.json?track_visit=true&forceLoad=true&_=1469021438604 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
