### ISSUE TITLE
HTTP Error 500 when trying to sign up or sign in

### ISSUE THREAD

**Issue by dawnguard** [freeCodeCamp/discourse-meta#36]
Note: I deleted my Github account and created another one with the same username. Could that have anything to do with this?

**Comment by m-henderson** [comment]
yea, please message me on gitter (@m-henderson) so that we can resolve your login issue.

**Comment by dawnguard** [comment]
I did.

**Comment by vdash2** [comment]
I am having the same issue

**Comment by dawnguard** [comment]
BUMP...

**Comment by dawnguard** [comment]
@QuincyLarson

**Comment by raisedadead** [comment]
Apologies for the delay, Michael (@m-henderson) will get back to you.

**Comment by m-henderson** [comment]
closing due to assumption of resolution.

**Comment by dawnguard** [comment]
nope :c

**Comment by m-henderson** [comment]
@dawnguard are you the one that messaged me on gitter ?

**Comment by m-henderson** [comment]
Re-opining due to multiple complaints of http 500 error during login.

**Comment by dawnguard** [comment]
Yeah

**Comment by m-henderson** [comment]
I believe this wan an issue due to multiple accounts being in our database. If you have any issues like this please contact me on gitter.
