### ISSUE TITLE
The forum is down / unresponsive

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/discourse-meta#37]
The forum is down and has been so off and on for the past couple hours.

During those brief times it comes back up, it's extremely sluggish - slow to the point of near unresponsiveness.

**Comment by P1xt** [comment]
Note: this is a repeat of https://github.com/freeCodeCamp/discourse/issues/35 which was closed in December

@BerkeleyTrue @m-henderson

**Comment by BerkeleyTrue** [comment]
Seems to working fine now. I'll ask the mods to keep an eye on it.


Happy Coding

**Comment by m-henderson** [comment]
We may need to upgrade our resources - i noticed this issue also.

**Comment by P1xt** [comment]
I asked in the chingu cohorts chat to ensure it wasn't just me, it was down/unresponsive for everybody for a couple hours.

**Comment by BerkeleyTrue** [comment]
Then it may be as @m-henderson says. We may need to increase the size of the droplet.

\cc @QuincyLarson

**Comment by P1xt** [comment]
This was closed prematurely - the underlying issue wasn't addressed and the forum is now down again.

**Comment by P1xt** [comment]
![fccforum](https://cloud.githubusercontent.com/assets/322175/23172766/7bac06e8-f81c-11e6-8262-c045a504565f.png)

**Comment by m-henderson** [comment]
@p1xt can you verify the URL In that picture ? Were you using https in the URL when you took that screen shot ?

**Comment by P1xt** [comment]
I still had the window open, the precise url is: https://forum.freecodecamp.com/

**Comment by P1xt** [comment]
The same url just worked now - the forum is going on and offline, cycling between the two every 5 minutes to 4 hours.

**Comment by m-henderson** [comment]
We are looking into this issue and will notify when it is resolved
