### ISSUE TITLE
Add "Help" buttons to forum navigation

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/discourse-meta#40]
@QuincyLarson commented on [Wed Jul 12 2017](https://github.com/freeCodeCamp/freeCodeCamp/issues/15636)

The forum is a great place to get near real-time help. The operative word here being "near". In practice, it takes 1 to 5 hours to get a response, which isn't fast enough for many people.

![admin_-_freecodecamp_forum](https://user-images.githubusercontent.com/985197/28133377-6bc7393e-6705-11e7-9390-34cf28a0f596.png)

The good news is we can significantly accelerate that process. We may be able to get the wait time for a response down to a few minutes.

We can do this by making it easier to browse posts that haven't yet been replied to (a vast majority of posts on the forum are either questions or requests for project feedback).

I think we should add two buttons to the forum navigation:

![](https://www.evernote.com/l/Ar_TaYM8kE1ONZ_J5Jxs8EG2Hx4ec4Jcs7oB/image.png)

[Answer Questions](https://forum.freecodecamp.org/?max_posts=1)

and

[Give Project Feedback](https://forum.freecodecamp.org/c/project-feedback?max_posts=1)

These could probably replace New and Unread which at the volume of posts we have aren't very useful. 

[Here is my discussion with Discourse](https://meta.discourse.org/t/whats-the-simplest-way-to-add-a-new-navigation-menu-item/65909)

And [here are the instructions they recommended we follow](https://meta.discourse.org/t/adding-unsolved-button-to-top-menu-using-custom-html/59758?source_topic_id=65909)

Would anyone be interested in trying to get this working?

---

@nsuchy commented on [Thu Jul 13 2017](https://github.com/freeCodeCamp/freeCodeCamp/issues/15636#issuecomment-314873704)

I think that adding an "Answer Questions" and "Give Project Feedback" buttons would be a good idea. You shouldn't have to wait 5 hours for a response, when you just want to keep coding and our stuck and can't get help quickly it can be frustrated. Clearly defining those buttons would be a good idea so people who want to help are more able to understand it.

**Comment by akshatbahety** [comment]
I would love to help
Are we looking to create a different webpage or just make those buttons redirect to a specific filtered forum list of question and answer ?

**Comment by m-henderson** [comment]
agreed

**Comment by QuincyLarson** [comment]
@akshatbahety We want to add these buttons seamlessly to the forum's navigation (like in the picture). These buttons will redirect to URLs that have the necessary filtering parameters right in the URL.

**Comment by m-henderson** [comment]
We can use JavaScript to add the buttons. @akshatbahety , we can work on this together if you like ?

**Comment by QuincyLarson** [comment]
@m-henderson Yes, we should try the method Discourse recommended:

[Here is my discussion with Discourse](https://meta.discourse.org/t/whats-the-simplest-way-to-add-a-new-navigation-menu-item/65909)

And [here are the instructions they recommended we follow](https://meta.discourse.org/t/adding-unsolved-button-to-top-menu-using-custom-html/59758?source_topic_id=65909)

**Comment by m-henderson** [comment]
Nice, will get this completed soon and will update when done. @akshatbahety

**Comment by QuincyLarson** [comment]
@m-henderson OK - great. Thanks for keeping me posted on this :)

**Comment by QuincyLarson** [comment]
@raisedadead @nsuchy @m-henderson After some further thought, I think we should first rely on the freecodecamp.org/contribute page directing people to these categories ("project feedback" and "help") instead of putting them in the navigation.

Thanks anyway for offering to help with this.
