### ISSUE TITLE
Edit profile photo in profile settings not possible

### ISSUE THREAD

**Issue by melluvia** [freeCodeCamp/discourse-meta#9]
I'm on mobile and can't seem to get how to edit the profile pic on mobile however everything else in settings seems to be customizable

**Comment by QuincyLarson** [comment]
@melluvia The photo should be locked to your GitHub photo. It looks like it is currently failing to successfully pull in your GitHub photo. I am closing this issue and we will fix the GitHub photo importation (https://github.com/FreeCodeCamp/discourse/issues/10).
